-- Full clean: inclui exclusão de usuários (atenção!)
BEGIN;
  TRUNCATE TABLE nft_transfers RESTART IDENTITY CASCADE;
  TRUNCATE TABLE nfts RESTART IDENTITY CASCADE;
  TRUNCATE TABLE collections RESTART IDENTITY CASCADE;
  TRUNCATE TABLE users RESTART IDENTITY CASCADE;
COMMIT;
