name: Create Backend ENV

on:
  workflow_dispatch:
  push:
    branches: [ master, dev-hiago ]
    paths:
      - '.github/workflows/**'
      - 'BackEnd/**'

jobs:
  create-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Criar .env com secrets
        run: |
          mkdir -p BackEnd
          cat > BackEnd/.env <<EOF
          PORT=${{ secrets.PORT }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_DATABASE=${{ secrets.DB_DATABASE }}
          EOF

      - name: Confirmar criação (sem mostrar valores)
        run: |
          echo "Arquivo .env criado com sucesso!"
          echo "Variáveis configuradas:"
          grep -o '^[^=]*' BackEnd/.env